openapi: 3.0.0
info:
  title: GildongE API
  version: "1.0.0"
servers:
  - url: http://localhost:8080
    description: Local server

tags:
  - name: Users
    description: 사용자 관련 API
  - name: DrivingPatterns
    description: 운전 패턴 관련 API
  - name: Consumables
    description: 소모품 교체 예정일 관련 API
  - name: CarModels
    description: 차량 모델 관련 API

paths:
  /api/users:
    post:
      tags: [Users]
      summary: 신규 사용자 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
      responses:
        "201":
          description: 생성 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: 잘못된 요청 (유효성 실패)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/users/login:
    post:
      tags: [Users]
      summary: 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "401":
          description: 인증 실패 (아이디 또는 비밀번호 불일치)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/auth/kakao/callback:
    get:
      tags: [Users]
      summary: 카카오 로그인 (인가 코드 기반)
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
          description: 카카오 인가 코드 (authorization code)
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: 잘못된 요청 (쿼리 누락, 토큰 요청 실패 등)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: 인증 실패 (유효하지 않은 인가 코드)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: 서버 오류 (내부 예외 등)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/users/{userId}:
    get:
      tags: [Users]
      summary: 사용자 조회
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: 사용자 고유 ID
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "404":
          description: 사용자 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags: [Users]
      summary: 사용자 정보(이름·비밀번호) 수정
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: 사용자 고유 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateRequest"
      responses:
        "200":
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: 사용자 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/patterns:
    post:
      tags: [DrivingPatterns]
      summary: 운전 패턴 기록 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DrivingPatternRequest"
      responses:
        "201":
          description: 생성 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DrivingPatternResponse"
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: 사용자 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/patterns/user/{userId}:
    get:
      tags: [DrivingPatterns]
      summary: 사용자별 운전 패턴 목록 조회
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: 사용자 고유 ID
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DrivingPatternResponse"
        "404":
          description: 사용자 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/patterns/username/{userName}:
    get:
      tags: [DrivingPatterns]
      summary: 사용자 이름 기준 운전 패턴 조회
      parameters:
        - name: userName
          in: path
          required: true
          schema:
            type: string
          description: 사용자 이름 (userName)
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DrivingPatternResponse"
        "404":
          description: 사용자 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/patterns/user/{userId}/weekly-averages:
    get:
      tags: [DrivingPatterns]
      summary: 사용자별 주(週) 단위 운전 점수 평균 조회
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: 사용자 고유 ID
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WeeklyAverageResponse"
        "404":
          description: 사용자 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/consumables:
    post:
      tags: [Consumables]
      summary: 소모품 교체 예정일 저장
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConsumableRequest"
      responses:
        "201":
          description: 저장 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsumableResponse"
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: 사용자 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/consumables/user/{userId}:
    get:
      tags: [Consumables]
      summary: 사용자별 소모품 내역 조회 (최신순)
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: 사용자 고유 ID
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ConsumableResponse"
        "404":
          description: 사용자 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/consumables/user/{userId}/overview:
    get:
      tags: [Consumables]
      summary: 전체 소모품 내역 + 다음 교체 예정일 조회
      description: |
        - `all`: 최신순으로 정렬된 전체 소모품 내역
        - `nextDueDate`: 가장 가까운(미래) 교체 예정일 (YYYYMMDD) 또는 `null`
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: 사용자 고유 ID
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsumablesOverviewResponse"
        "404":
          description: 사용자 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/car-models:
    get:
      tags: [ CarModels ]
      summary: 전체 차량 모델 목록 조회
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CarModelResponse"

    post:
      tags: [ CarModels ]
      summary: 차량 모델 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CarModelRequest"
      responses:
        "201":
          description: 등록 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarModelResponse"
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/car-models/manufacturer/{manufacturer}:
      get:
        tags: [ CarModels ]
        summary: 제조사 기준 차량 모델 조회
        parameters:
          - name: manufacturer
            in: path
            required: true
            schema:
              type: string
            description: 제조사명
        responses:
          "200":
            description: 조회 성공
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/CarModelResponse"

  /api/car-models/model/{modelName}:
      get:
        tags: [ CarModels ]
        summary: 차량 모델명 기준 조회
        parameters:
          - name: modelName
            in: path
            required: true
            schema:
              type: string
            description: 차량 모델명
        responses:
          "200":
            description: 조회 성공
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/CarModelResponse"

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: 에러 코드
        message:
          type: string
          description: 에러 메시지

    AuthProvider:
      type: string
      description: 로그인 제공자
      enum:
        - LOCAL
        - KAKAO
        - GOOGLE
        - NAVER

    UserCreateRequest:
      type: object
      required:
        - loginId
        - password
        - userName
        - provider
      properties:
        loginId:
          type: string
          description: 로그인용 아이디
        password:
          type: string
          description: 비밀번호
        userName:
          type: string
          description: 실명
        provider:
          $ref: "#/components/schemas/AuthProvider"
          description: 로그인 제공자 (LOCAL 또는 Social)

    LoginRequest:
      type: object
      required:
        - loginId
        - password
      properties:
        loginId:
          type: string
          description: 로그인용 아이디
        password:
          type: string
          description: 비밀번호

    UserUpdateRequest:
      type: object
      required:
        - userName
      properties:
        userName:
          type: string
          description: 변경할 실명
        password:
          type: string
          description: 변경할 비밀번호 (선택)

    UserResponse:
      type: object
      properties:
        id:
          type: string
          description: 사용자 고유 ID
        loginId:
          type: string
          description: 로그인용 아이디
        userName:
          type: string
          description: 실명
        avgDrivingScore:
          type: number
          format: float
          description: 평균 운전 점수
        createdAt:
          type: string
          format: date-time
          description: 생성 시각
        provider:
          $ref: "#/components/schemas/AuthProvider"
          description: 로그인 제공자

    DrivingPatternRequest:
      type: object
      required:
        - userId
        - drivingScore
      properties:
        userId:
          type: string
          description: 사용자 고유 ID
        drivingScore:
          type: number
          format: float
          description: 운전 점수

    DrivingPatternResponse:
      type: object
      properties:
        id:
          type: string
          description: 기록 고유 ID
        userId:
          type: string
          description: 사용자 고유 ID
        drivingScore:
          type: number
          format: float
          description: 운전 점수
        recordedAt:
          type: string
          format: date-time
          description: 기록 시각

    WeeklyAverageResponse:
      type: object
      properties:
        weekStart:
          type: string
          format: date
          description: 해당 주의 시작일 (월요일, YYYY-MM-DD)
        averageScore:
          type: number
          format: float
          description: 그 주의 평균 운전 점수

    ConsumableRequest:
      type: object
      required:
        - userId
        - carModel
        - carNumber
      properties:
        userId:
          type: string
          description: 사용자 고유 ID
        carModel:
          type: string
          description: 차량 모델명
        carNumber:
          type: string
          description: 차량 번호
        engineOilDate:
          type: string
          pattern: '^[0-9]{8}$'
          description: 엔진 오일 교체 예정일 (YYYYMMDD)
        batteryDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 배터리 교체 예정일 (YYYYMMDD)
        coolantDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 부동액 교체 예정일 (YYYYMMDD)
        transmissionOilDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 변속기 오일 교체 예정일 (YYYYMMDD)
        brakeOilDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 브레이크 오일 교체 예정일 (YYYYMMDD)
        airconFilterDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 에어컨 필터 교체 예정일 (YYYYMMDD)
        engineOilChangedDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 엔진 오일 교체 완료일 (YYYYMMDD)
        batteryChangedDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 배터리 교체 완료일 (YYYYMMDD)
        coolantChangedDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 부동액 교체 완료일 (YYYYMMDD)
        transmissionOilChangedDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 변속기 오일 교체 완료일 (YYYYMMDD)
        brakeOilChangedDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 브레이크 오일 교체 완료일 (YYYYMMDD)
        airconFilterChangedDate:
          type: string
          pattern: '^[0-9]{8}$'
          nullable: true
          description: 에어컨 필터 교체 완료일 (YYYYMMDD)




    ConsumableResponse:
      type: object
      properties:
        id:
          type: string
          description: 소모품 내역 고유 ID
        userId:
          type: string
        carModel:
          type: string
        carNumber:
          type: string
        engineOilDate:
          type: string
        batteryDate:
          type: string
        coolantDate:
          type: string
        transmissionOilDate:
          type: string
        brakeOilDate:
          type: string
        airconFilterDate:
          type: string
        engineOilChangedDate:
          type: string
          description: 엔진 오일 교체 완료일
        batteryChangedDate:
          type: string
          description: 배터리 교체 완료일
        coolantChangedDate:
          type: string
          description: 부동액 교체 완료일
        transmissionOilChangedDate:
          type: string
          description: 변속기 오일 교체 완료일
        brakeOilChangedDate:
          type: string
          description: 브레이크 오일 교체 완료일
        airconFilterChangedDate:
          type: string
          description: 에어컨 필터 교체 완료일

        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time


    ConsumablesOverviewResponse:
      type: object
      properties:
        all:
          type: array
          items:
            $ref: "#/components/schemas/ConsumableResponse"
        nextDueDate:
          type: string
          description: 가장 가까운(미래) 교체 예정일 (YYYYMMDD) 또는 null

    CarModelResponse:
      type: object
      properties:
        id:
          type: string
          description: 모델 고유 ID
        manufacturer:
          type: string
        modelName:
          type: string
        modelYear:
          type: string
        fuelType:
          type: string
        bodyType:
          type: string
        manualUrl:
          type: string
          description: 차량 매뉴얼 URL

    CarModelRequest:
      type: object
      required:
        - manufacturer
        - modelName
        - modelYear
        - fuelType
        - bodyType
        - manualUrl
      properties:
        manufacturer:
          type: string
          description: 제조사
        modelName:
          type: string
          description: 모델명
        modelYear:
          type: string
          description: 연식
        fuelType:
          type: string
          description: 연료 타입
        bodyType:
          type: string
          description: 차종
        manualUrl:
          type: string
          description: 차량 매뉴얼 URL
